---
- name: Clone repo branch
  git:
    repo: '{{ nimbus_eth1_repo_url }}'
    version: '{{ nimbus_eth1_repo_branch }}'
    dest: '{{ nimbus_eth1_repo_path }}'
    force: true
    update: true
  become_user: '{{ nimbus_eth1_service_user }}'

- name: Create build script
  template:
    src: 'build.sh.j2'
    dest: '{{ nimbus_eth1_build_script_path }}'
    owner: '{{ nimbus_eth1_service_user }}'
    group: '{{ nimbus_eth1_service_group }}'
    mode: 0775

- name: Check if node binary link exists
  stat:
    path: '{{ nimbus_eth1_repo_path }}/build/nimbus_execution_client'
  register: nimbus_eth1_bin

- name: Create timer for build script
  include_role: name=infra-role-systemd-timer
  vars:
    systemd_timer_name: '{{ nimbus_eth1_build_service_name }}'
    systemd_timer_user: '{{ nimbus_eth1_service_user }}'
    systemd_timer_group: '{{ nimbus_eth1_service_group }}'
    systemd_timer_description: 'Build {{ nimbus_eth1_service_name }}'
    systemd_timer_start_on_creation: '{{ not nimbus_eth1_bin.stat.exists }}'
    systemd_timer_consul_warning: true
    systemd_timer_enabled: '{{ nimbus_eth1_build_timer_enabled }}'
    systemd_timer_frequency: '{{ nimbus_eth1_build_frequency }}'
    systemd_timer_timeout_sec: '{{ nimbus_eth1_build_timer_timeout }}'
    systemd_timer_work_dir: '{{ nimbus_eth1_service_path }}'
    systemd_timer_script_path: '{{ nimbus_eth1_build_script_path }}'
