---
- name: Create directories
  file:
    path:   '{{ item }}'
    owner:  '{{ nimbus_eth1_service_user }}'
    group:  '{{ nimbus_eth1_service_group }}'
    state:  'directory'
    mode:   0775
  with_items:
    - '{{ nimbus_eth1_service_path }}'
    - '{{ nimbus_eth1_data_path }}'

- name: Create JSON RPC wrapper script
  template:
    src:    'rpc.sh.j2'
    dest:   '{{ nimbus_eth1_rpc_script_path }}'
    owner:  '{{ nimbus_eth1_service_user }}'
    group:  '{{ nimbus_eth1_service_group }}'
    mode:   0755
  when: nimbus_eth1_rpc_enabled

- name: Create JWT shared secret file
  copy:
    dest:     '{{ nimbus_eth1_jwt_secret_path }}'
    content:  '{{ nimbus_eth1_jwt_secret }}'
    owner:    '{{ nimbus_eth1_service_user }}'
    group:    '{{ nimbus_eth1_service_group }}'
    mode:     0400
  when: nimbus_eth1_jwt_secret is defined
