---
- name: 'Create Consul service definition'
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ nimbus_eth1_consul_service_file_name }}'
    consul_services:
      - id: '{{ nimbus_eth1_service_name }}'
        name: '{{ nimbus_eth1_consul_service_name }}'
        port: '{{ nimbus_eth1_listening_port }}'
        address: '{{ nimbus_eth1_public_address }}'
        tags: ['{{ env }}.{{ stage }}', 'nimbus-eth1']
        # WARNING: Nimbus runs on one thread and RPC calls regularly time out.
        #checks:
        #  - name: '{{ nimbus_eth1_consul_service_name }}-health'
        #    type: 'script'
        #    script: '{{ nimbus_eth1_cont_vol }}/rpc.sh eth_syncing'
        #    interval: '60s'
        #    timeout: '10s'

      - id: '{{ nimbus_eth1_service_name }}-metrics'
        name: '{{ nimbus_eth1_consul_metrics_service_name }}'
        port: '{{ nimbus_eth1_metrics_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        tags: ['{{ env }}.{{ stage }}', 'nimbus-eth1', 'metrics']
        meta:
          container: '{{ nimbus_eth1_service_name }}'
        checks:
          - name: '{{ nimbus_eth1_consul_metrics_service_name }}-health'
            type: 'http'
            http: 'http://localhost:{{ nimbus_eth1_metrics_port }}/metrics'
