---
- name: 'Create Consul service definition'
  include_role:
    name: infra-role-consul-service
  vars:
    consul_config_name: '{{ nimbus_eth1_consul_service_file_name }}'
    consul_default_check_disabled:           '{{ nimbus_eth1_consul_check_disabled }}'
    consul_default_check_interval:           '{{ nimbus_eth1_consul_check_interval }}'
    consul_default_check_timeout:            '{{ nimbus_eth1_consul_check_timeout }}'
    consul_default_success_before_passing:   '{{ nimbus_eth1_consul_success_before_passing }}'
    consul_default_failures_before_warning:  '{{ nimbus_eth1_consul_failures_before_warning }}'
    consul_default_failures_before_critical: '{{ nimbus_eth1_consul_failures_before_critical }}'
    consul_services:
      - id: '{{ nimbus_eth1_service_name }}'
        name: '{{ nimbus_eth1_consul_service_name }}'
        port: '{{ nimbus_eth1_listening_port }}'
        address: '{{ nimbus_eth1_public_address }}'
        tags: ['{{ env }}.{{ stage }}', 'nimbus-eth1']
        checks:
          - id: '{{ nimbus_eth1_service_name }}-health'
            type: 'script'
            script: '{{ nimbus_eth1_service_path }}/rpc.sh eth_syncing'

      - id: '{{ nimbus_eth1_service_name }}-metrics'
        name: '{{ nimbus_eth1_consul_metrics_service_name }}'
        port: '{{ nimbus_eth1_metrics_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        tags: ['{{ env }}.{{ stage }}', 'nimbus-eth1', 'metrics']
        meta:
          container: '{{ nimbus_eth1_service_name }}'
        checks:
          - id: '{{ nimbus_eth1_service_name }}-metrics-health'
            type: 'http'
            http: 'http://localhost:{{ nimbus_eth1_metrics_port }}/health'
