---
- name: Open ports in iptables firewall
  include_role: name=open-ports
  vars:
    open_ports_default_comment: '{{ nimbus_eth1_service_name }}'
    open_ports_default_chain: 'SERVICES'
    open_ports_list:
      - { port: '{{ nimbus_eth1_listening_port }}', protocol: 'tcp' }
      - { port: '{{ nimbus_eth1_discovery_port }}', protocol: 'udp' }
      - { port: '{{ nimbus_eth1_metrics_port }}',   chain: 'VPN', ipset: 'metrics.hq' }
