---
- name: Symlink service logs folder
  file:
    src: '/var/log/service/{{ nimbus_eth1_service_name }}'
    dest: '{{ nimbus_eth1_logs_link }}'
    state: 'link'
    force: true

- name: Create systemd Unit file
  template:
    src: 'nimbus-eth1.service.j2'
    dest: '/etc/systemd/system/{{ nimbus_eth1_service_name }}.service'
    mode: 0644

- name: Reload systemctl
  command: systemctl daemon-reload

- name: Restart the service
  service:
    name: '{{ nimbus_eth1_service_name }}.service'
    state: 'restarted'
    enabled: true
