---
- name: Symlink service logs folder
  file:
    src: '/var/log/service/{{ nimbus_eth1_service_name }}'
    dest: '{{ nimbus_eth1_logs_link }}'
    state: 'link'
    force: true

- name: Create systemd Unit file
  template:
    src: 'nimbus-eth1.service.j2'
    dest: '/etc/systemd/system/{{ nimbus_eth1_service_name }}.service'
    mode: 0644
  register: nimbus_eth1_service_definition

- name: Restart the service
  service:
    name: '{{ nimbus_eth1_service_name }}.service'
    enabled: true
    daemon_reload: true
    state: |-
      {{
      (
        nimbus_eth1_service_definition.changed or
        nimbus_eth1_service_force_restart
      ) | ternary("restarted", "started") }}
